### ISSUE TITLE
Bug with generated pointer

### ISSUE THREAD

**Issue by JustForNothing** [BullyWiiPlaza/JGeckoU#14]
I use the latest version of the code handler, and when I use the pointer generator, it crash :(

Anyway to fix that ?

**Comment by BullyWiiPlaza** [comment]
Yes, the generated pointer code is wrong.

**Comment by JustForNothing** [comment]
Do you have an example for [10685548]+850 ? 
Because I don't understand how that work
memory range is 20000000-25000000

**Comment by BullyWiiPlaza** [comment]
I didn't care yet but check the first post [here](https://gbatemp.net/threads/post-your-wiiu-cheat-codes-here.395443/).

**Comment by JustForNothing** [comment]
please add that for the next update, I really need it :(

**Comment by CuriousTommy** [comment]
@JustForNothing I think it would be something like this
```
A Code Just for Something [JustForNothing]
30000000 10685548 // Tells code to load pointer value
20000000 25000000 // Tells code where the range is
31000000 00000850 // Add the offset to the pointer value
00120000 VVVVVVVV // Do a 32bit code write 
```

**Comment by JustForNothing** [comment]
30000000 10685548 // Tells code to load pointer value
20000000 25000000 // Tells code what the range is
31000000 00000850 // Add the offset to the pointer value
00120000 VVVVVVVV // Do a 32bit code write 

what is 3000000 and 31000000 ?

**Comment by CuriousTommy** [comment]
`30000000` Loads the pointer while `31000000` add the offset to pointer.

It is probably better if we bring this discussion to [this thread](https://gbatemp.net/threads/post-your-wiiu-cheat-codes-here.395443/). I can help you there if you are still confused.

**Comment by JustForNothing** [comment]
oh wow that simple I feel stupid now

**Comment by JustForNothing** [comment]
how can I make an if equal with a pointer ?
sorry I don't have a gbatemp account, [s]and it's a JgeckoU issue if he can't generate new pointer ( ͡° ͜ʖ ͡°)[/s]

**Comment by CuriousTommy** [comment]
It okay. When I first started, there were a lot of stupid mistakes I did (and still do to this day).

I would prefer if we continue our discussion in GBAtemp since I don't want to have constant email notification be sent to BullyWiiPlaza. Plus this issue should be discussing the issue related to BullyWiiPlaza implementing the new code types. The Issue thread isn't a really meant to be a help forum.

I ask if kindly if you can make a GBAtemp account so I can help you. My username is the same as on GitHub. Also, I recommend you first read the Cafe-Code-Type Documentary first in the thread that I linked to you. It shows various code types (such as RAM Write, if conditions, following pointers, etc.) and gives examples there.

**Comment by JustForNothing** [comment]
ok check your gbatemp PM
