### ISSUE TITLE
Where is the source?

### ISSUE THREAD

**Issue by mancoast** [BullyWiiPlaza/JGeckoU#26]
Ok, I have read http://gbatemp.net/threads/development-of-new-wii-u-ram-debugger.413477/

I see that you were inspired by https://github.com/Chadderz121/tcp-gecko-dotnet

Do you intend to keep this closed source?
How do we collaborate?!?

Please explain the LICENSE

**Comment by BullyWiiPlaza** [comment]
It will stay closed source because of certain people disrespecting and the license means you can only download it from this repository and use it. Reuploading the tool is not allowed just like reverse engineering it. The way you can collaborate is [here](https://gbatemp.net/threads/tcp-gecko-server-feature-requests.428135/) for the `TCP Gecko Installer` and make `JGecko U` suggestions [here](https://gbatemp.net/threads/jgecko-u-setup-guide.426292/). It is more useful to contribute to the TCP Gecko Installer though and it's open source and will always be due to the GPL.
