### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by Megabyte918** [BullyWiiPlaza/JGeckoU#32]
Thank you @BullyWiiPlaza for making this program. It's amazing :)

I'd like to report a few bugs I experienced with this version of JGecko U that have been bothering me.

- After canceling a search in the search tab, all buttons become greyed-out and cannot be fixed unless you restart the program.
- Opening the "Memory Viewer" tab while a search is in progress results in a crash, and throws [these two errors.](https://i.imgur.com/7XCU7vt.png)
- Not sure if this is a bug or not or it is intended to be so, but opening the "add code" window prevents the user from interacting with the rest of the program. You can't click on any tabs, or anything else in the background of the window.  It's very annoying when you switch to another window for example, then switch back forgetting you had the add code window open, try to click on a tab, and the clicks get blocked. And if you are adding code and need to switch back to the "memory viewer" tab for example, you have to close the add code window to get to it, then reopen it once you have what you need.
- Any menu that spawns from the conversions tab dissapears when it is put behind the program (linux only)

**Comment by BullyWiiPlaza** [comment]
Hi, thank you 👍 

* This forces a reconnect so the buttons will be greyed out till it reconnected which should only take a fraction of a second.
* This is not possible because when you're searching you can't send any more commands to the Wii U until it is finished. It will freeze the entire interface till the search completed and then updates the memory viewer. I will most likely grey them out while searching so users won't switch to those but anything that communicates with the Wii U would get stuck till the search is completed.
* This can be changed in 1 line of code so I'll do that.
* The conversions dialogs don't disappear. They're still there behind the main frame.

**Comment by Megabyte918** [comment]
Thanks for taking the time to respond to this and fix it.
About the linux thing: I tested it again and it seems couldn't reproduce the same effect. Weird, maybe it was just a one-time thing :P
