### ISSUE TITLE
Android?

### ISSUE THREAD

**Issue by boss69xd** [BullyWiiPlaza/JGeckoU#54]
Would it be possible to make JGecko U on android, like an app?

**Comment by BullyWiiPlaza** [comment]
Yes, I even started something back in the day. You can see it [`here`](https://www.youtube.com/watch?v=KiX76MGMvgs). It's an Android app which can read/write the Wii U RAM like `JGecko U` but I won't continue it anymore since it's too much work and I personally don't need something like this. I know many people would like this though since it's arguably pretty cool.

**Comment by BullyWiiPlaza** [comment]
I'm closing this issue since it won't be done but it would be possible. It's just too much work and there is no reasonable support from the community for such a big project besides a handful of people who might just want to use it.
