### ISSUE TITLE
DarkFlare

### ISSUE THREAD

**Issue by TheNeutral-i** [BullyWiiPlaza/JGeckoU#55]
So earlier, someone posted an issue about how the stalker code wasn't working
https://github.com/BullyWiiPlaza/JGeckoU/issues/52

However, in my instance, I have the newest JGeckoU and TCPGecko combo and the codes do send, but instantly crash my game. You said that it "worked" for you, does that mean it was playable or simply that it was sent? I really don't understand why this keeps happening. I'm not the first to encounter this, and I won't be the last. Any help on finally resolving this issue would be greatly appreciated.

- Thank you.

**Comment by BullyWiiPlaza** [comment]
This is not how it works. If someone makes a code which doesn't work, you firstly ask that person, not me. If that person (= the code maker) realizes there is a bug in JGecko U *then* they can open an issue. NOT users who can't use codes (because they don't understand what could be wrong).

Anyway, you have to add the value 4E800020 at the end of the last raw assembly code in the code list to make it work and not crash.
