### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException

### ISSUE THREAD

**Issue by Youlose2019** [BullyWiiPlaza/JGeckoU#61]
After downloading  JGecko U, I got this message and don't know how to fix.

javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to request target

Thanks for your help.

**Comment by BullyWiiPlaza** [comment]
> The error message indicates that Artifactory could not establish a trusted connection over SSL (you may see this issue if you are using Self-Signed certificate or a certificate that is issued by an internal Certificate Authority or if your clients (e.g. browser, java) are outdated). The trust is handled by having root and intermediate certificates of your SSL certificate on a trusted keystore.

[Source](https://jfrog.com/knowledge-base/how-to-resolve-unable-to-find-valid-certification-path-to-requested-target-error).

This issue seems to be caused by an outdated browser or `Java`. Experience has shown that this is probably caused by `Java 11`. Please try installing [`Java 12`](https://www.oracle.com/technetwork/java/javase/downloads/jdk12-downloads-5295953.html) and/or update your browser/operating system.
