### ISSUE TITLE
Cant connect to wii u

### ISSUE THREAD

**Issue by AnyLastWords** [BullyWiiPlaza/JGeckoU#77]
![error](https://user-images.githubusercontent.com/68654921/88197566-82339280-cbf7-11ea-9429-5f0d95379552.PNG)
Ive just started doing this recently and all i really have is a homebrewed wii u with tcp gecko and mocha cfw installed I dont know why i cant connect.

**Comment by BullyWiiPlaza** [comment]
The error message you posted is from the Wii U Finder option. I assume you tried to enter your Wii U's IP address manually already and it didn't connect? Make sure your PC is in the same subnet as your Wii U so the connection can succeed. Furthermore, you need to have ran the TCP Gecko Installer of course. On every Wii U restart you need to run the TCP Gecko Installer again since it is not permanently installed. I'm able to connect so you're probably doing something wrong, try everything I listed before.

**Comment by AnyLastWords** [comment]
yes i tryed to put in my ip but it wouldnt connect by subnet do you mean network im on the same network but one is connected to the wifi router and the other is straight to the internet does that affect this? I have installed tp gecko
